### PR TITLE
Run AOT compilation in single process

### PR DESCRIPTION
**Pull request by stefanroex**
If you AOT compile multiple namespaces, every namespaces is compiled in a separate subprocess. For larger projects this is very slow. This PR makes sure the compilation is done in a single subprocess for increased performance.

### CODE REVIEW

**Comment by seancorfield** [comment]
Thanks. I'll take a look at this when I'm next doing an OSS spike. I'm planning to split `depstar` up into a number of "tasks" that can be run in a pipeline via `-X` (now that it supports multiple functions and can essentially thread exec arguments through them). That will substantially change the structure of how AOT is done in `depstar` but I'll bear this multi-ns compile issue in mind when I take that on (I may still merge this prior to the task rework -- just not sure yet).

**Comment by stefanroex** [comment]
@seancorfield Sounds good 👍 Thanks!

**Comment by seancorfield** [comment]
FYI: I've split `depstar` into three "tasks" (pom create/sync, AOT compilation, JAR building). These are not directly exposed yet (work in progress) but this has moved all the AOT compilation into a separate namespace which is which your PR will no longer merge -- but it is still on my radar as an optimization.

**Comment by stefanroex** [comment]
Thanks for the update . I’m happy to apply a similar optimization in the new task structure. Also if you’re planning to do further refactoring in the AOT namespace, let me know, maybe I’m able to help? Just let me know 👍.

**Comment by seancorfield** [comment]
Thanks for the pull request. I made a couple of adjustments, including a way to force compilation into multiple batches if there are a large number of namespaces being compiled.

**Pull request closed without merging**
