### PR TITLE
Exclude .DS_Store by default

### PR DESCRIPTION
**Pull request by alexisvincent**

### CODE REVIEW

**Comment by seancorfield** [comment]
Since these are regex, the `.` should be escaped. It should also probably exclude `.DS_Store` files in any folder (which your change does not).

**Comment by seancorfield** [comment]
@alexisvincent Do you want to update your PR to address my comments?

**Comment by seancorfield** [comment]
I'm close to cutting a new release so I've gone ahead and added `.DS_Store` to the excluded files list (full path) and added a test for some of those files -- which is why this PR won't merge. No action needed from you -- thank you for bringing `.DS_Store` to my attention as something that ought to be ignored!

**Comment by alexisvincent** [comment]
Thanks Sean! Sorry for the poorly formed PR. Glad to see this in the latest version!

**Pull request closed without merging**
