### PR TITLE
Add main class override option

### PR DESCRIPTION
**Pull request by stathissideris**

### CODE REVIEW

**Comment by stathissideris** [comment]
Haha, unfortunate timing and conflict! Is there any point keeping my documentation on this? It would certainly need some restructuring to make it make sense.

**Comment by seancorfield** [comment]
I added the `-m` option two weeks ago and released it in 3.1. I'll take a look at your suggested README changes when I get back to work and see whether I want to add similar anything additional to the changes I added for `-m` but I'm closing this out (there are several typos and I'm not sure I want to go into that much detail about using `compile` because I honestly don't want to have to support that usage -- I'd rather folks learned about how to do AOT elsewhere since I am fairly adamantly against it).

**Comment by stathissideris** [comment]
Well, the typos are embarassing! I'm sorry, I should have avoided raising this request when I was so sleep deprived. I didn't mean to imply that we made the change at the same time, although I have been sitting on it for about 3 weeks. I completely understand if you'd rather not promote AOT!

**Comment by seancorfield** [comment]
FWIW, here's what the README currently says about using `-m`:

Finally, if you have a `pom.xml` file and also include a (compiled) class in your JAR file that contains a `main` function, you can use the `-m` / `--main` option to specify the name of that class as the `Main-Class` in the manifest instead of the default (`clojure.main`):
```
# compile your main class onto your classpath somehow
# then build your uberjar:
clojure -A:depstar -m hf.depstar.uberjar MyProject.jar -m my.EntryPoint
# now you can run it like this:
java -jar MyProject.jar
# that will run my.EntryPoint's main function
```
I'm not sure I want to elaborate on `compile your main class onto your classpath somehow` which is really the main part of your suggested change. Thoughts?

**Pull request closed without merging**
